apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: csi-pvc
